### ISSUE TITLE
Views extension not being displayed

### ISSUE THREAD

**Issue by vladox** [brain-tec/swisspost-odoo-yellowcube#17]
While debugging the source to see where the value for the xml element "MinRemLife" is generated we have noticed that some views extensions are not showing up on the products (see screenshot attached). The views not being loaded are product_expiry_view_ext.xml product_product_ext_view.xml.
We were wondering if this is a known problem and if you were experiencing the same in your reference installation.

![screenshot_20_10_16_21_24](https://cloud.githubusercontent.com/assets/2648461/19574674/a55cc0da-970b-11e6-91b3-0b61d9728d1b.png)

**Comment by BT-mfasola** [comment]
the code is here:
https://github.com/brain-tec/swisspost-odoo-yellowcube/blob/45afe9809aaf29aea04d5455ff3c98f57b6075ac/pc_connect_master/views/product_expiry_view_ext.xml#L12

**Comment by ghost** [comment]
That view was declared over product.product, but it inherited a product.template view, so it never was shown. Now, that view, and its fields, are moved into product.template.
