### ISSUE TITLE
AttributeError: 'purchase.order' object has no attribute 'warehouse_id' in pc_connect_master/purchase_order_ext.py

### ISSUE THREAD

**Issue by jclopezar** [brain-tec/swisspost-odoo-yellowcube#4]
pc_connect_master/purchase_order_ext.py", line 41, 
in _set_destination_location  
input_location_of_warehouse = purchase_order.warehouse_id.lot_input_id
AttributeError: 'purchase.order' object has no attribute 'warehouse_id'

IMHO:  purchase_order.location_id.warehouse_id.lot_input_id

Or there is some dependency missing

**Comment by ghost** [comment]
Please, if you can post the link to the file (we have multiple versions) it will be easier to have a look at that :+1:

**Comment by jclopezar** [comment]
Sure, it is in version 8
https://github.com/brain-tec/swisspost-odoo-yellowcube/blob/8.0/pc_connect_master/purchase_order_ext.py

**Comment by BT-mfasola** [comment]
IMHO: 
either (short and imho questionable): purchase_order.location_id
(there is really no reason to take the location from the warehouse from the location...)
or (and that being the way to do it): purchase_order.picking_type_id.default_location_dest_id
=> so whatever route is configured for purchases, the location of that rout will be considered to receive the products

**Comment by BT-mfasola** [comment]
btw: code in question is here:
https://github.com/brain-tec/swisspost-odoo-yellowcube/blob/8.0/pc_connect_master/purchase_order_ext.py#L41

**Comment by BT-mfasola** [comment]
PR created: #11
