### ISSUE TITLE
View Delivery Order button can lead to empty delivery order

### ISSUE THREAD

**Issue by rruebner** [brain-tec/swisspost-odoo-yellowcube#51]
Hi,

you overwrote the button **View Delivery Order** from sale_stock.view_order_form_inherit in pc_connect_master/views/stock_view_ext.xml.
The invisible attribute update lead to the problem that the delivery button is visible even when the sale order has set **Create Invoice: Before Delivery** and the invoice is not paid. If you click on the delivery button now you will be forwarded to an empty delivery order view. If the invoice is paid completely the delivery button shows the correct delivery order.

To fix it you have to update the invisible attribute.

Change
```
attrs="{'invisible': ['|',('picking_ids','in',(False,[])),('state', 'not in', ('progress','manual'))]}"
```

to

```
attrs="{'invisible': ['|','|',('picking_ids','=',False),('picking_ids','=',[]),('state', 'not in', ('progress','manual'))]}" 
```

If this is fine should I create a pull request or do you change the small code change by yourself?

Regards, Robert

**Comment by ghost** [comment]
Please, create a PR :+1:
