### ISSUE TITLE
Release for Odoo 10

### ISSUE THREAD

**Issue by olivierb2** [brain-tec/swisspost-odoo-yellowcube#92]
Hello,

Do you plan to release this swisspost module with Odoo 10?

Thanks

Olivier.

**Comment by BT-nleutenegger** [comment]
Hi Olivier

At the moment, there is no plan to port to and release the module in Odoo v.10

Kind regards
Nathanael

**Comment by olivierb2** [comment]
Hi,

Thanks for the information.

Regards.

Olivier.
